name: Janet Jackson
age: 30
email: hocquard@gmail.com
address:
  street: 44 Broadway Street
  city: New York
  state: New York
  zip: 10001
status:
  account: true
  subscription: premium
occupation: actress
