name: zsync

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    name: Repo Sync
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commit
        run: |
          git config --global user.name 'jimhoc94'
          git config --global user.email 'jimhoc94@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push
