name: zsync

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      number_API_calls:
        description: "number of API calls"
        required: true
        type: number
        default: 1
      pwd:
        description: "pwd"
        required: true
        type: string

jobs:
  Sync:
    runs-on: ubuntu-latest
    name: Repo Sync
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: jimhoc94/zsync
          ref: "main"
          path: tools/zsync
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: zSync
        env:
          MAINFRAME_PASSWORD_A: ${{ secrets.MAINFRAME_PASSWORD }}
        run: node ./tools/zsync/dist/index.js ${{ github.event.inputs.number_API_calls }}  ${{ secrets.MAINFRAME_PASSWORD }} ${{ github.event.inputs.pwd }}
      - name: Detete tools directorie
        run: |
          rm -R tools
          tree .
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
