name: zsync

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      number_API_calls:
        description: "number of API calls"
        required: true
        type: number
        default: 1
      password:
        description: "mainframe password"
        required: true
        type: string

jobs:
  Sync:
    runs-on: ubuntu-latest
    name: Repo Sync
    steps:
      - name: Mask Password
        run: |
        API_PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
        echo ::add-mask::$API_PASSWORD
        echo API_PASSWORD=$API_PASSWORD >> $GITHUB_ENV    
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: jimhoc94/zsync
          ref: "main"
          path: tools/zsync
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: node ./tools/zsync/dist/index.js ${{ github.event.inputs.number_API_calls }} ${{ env.API_PASSWORD }}
      - run: rm -R tools
      - run: tree .
      - name: Commit
        run: |
          git config --global user.name 'jimhoc94'
          git config --global user.email 'jimhoc94@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push
